- name: Print user and password
# how to give varibles through prompt
  hosts: local
  connection: local
  vars-prompt:
   - name: username
     prompt: Please enter username
     private: false

   - name: password
     prompt: Please enter password
     pricate: true

  tasks:
    - name : print info
      ansible.builtin.debug:
        msg: "username is: {{ username }}, password is: {{ password }}"